### ISSUE TITLE
Mencoba menambah issue dan close issue ini

### ISSUE THREAD

**Issue by wijatmoko** [mindatama/GIT#1]
mencoba menambah issue dan close isue ini. ini adalah komentar untuk issue, sebenarnya tidak ada issue tapi dengan menambah issue ini diharap kata yang diketik panjang dan mohon maaf telah bertele tele.. 

- [x] satu issue mencoba
- [x] dua issue
- [x] issue terakhir yang di centang

1. satu 
2. dua 
3. tiga

mencoba mention @mindatama

**Comment by mindatama** [comment]
untuk check list satu issue mencoba done dengan mengisi centangan

**Comment by mindatama** [comment]
mencoba merilis issue kedua dengan aplikasi git di hp. ternyata ketika kita memiliki repo dan orang lain create issue, pada nitifikasi tidak nampak kecuali kita di tag atau seperti misal: @wijatmoko

**Comment by wijatmoko** [comment]
mencoba me rilis isue ketiga. ternyata walaupun tidak ada di notifikasi pada @mindatama tetapi seluruh email mendapat pemberitahuan bahwa ada komentar, wijatmoko.m@bukitmakmur.com dan mindatama@gmail.com. keren!

**Comment by mindatama** [comment]
selesai, terimakasih
